build:
  version: "2.0"

accounts:
  message: "Welcome to accounts related QA APIs "
  contactDetails:
    name: "Ujang - QA Lead"
    email: "ujang@account.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371