info:
  dev: "Ichwan Sholihin"

accounts:
  description: "This is properties for accunts"
  details:
    project: "microservices"
    version: "1.0"
  helps:
    - 0857 6668-9697
    - 0821 1310-6437
