build:
  version: "3.0"

loans:
  message: "Welcome to loans related local APIs "
  contactDetails:
    name: "Ardi - Dev"
    email: "ardi@loans.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934