build:
  version: "1.0"

loans:
  message: "Welcome to loans related prod APIs "
  contactDetails:
    name: "Darmian - Product Owner"
    email: "darmian@loans.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956