server:
  port: 8080
  spring:
    application:
      name: "accounts"
    config:
      import: "optional:configserver:http://localhost:8071/"
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password: ''
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true

info:
  dev: "Ichwan Sholihin"

accounts:
  description: "This is properties for accunts"
  details:
    project: "microservices"
    version: "1.0"
  helps:
    - 0857 6668-9697
    - 0821 1310-6437
