spring:
  application:
    name: "configserver"
  profile:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ichwansh03/docker-config-server.git"
          default-label: "feat/config-server"
        bootstrap: true

server:
  port: 8071